### ISSUE TITLE
NOTE: the reason of forking this repository

### ISSUE THREAD

**Issue by sio4** [gobuffalo/github_flavored_markdown#8]
This repository was forked from https://github.com/shurcooL/github_flavored_markdown in late 2018 to fix the dependency issue.
Currently, there is no significant functional fragmentation so far and it could be fine to keep it as is. 

The related PRs are:
* https://github.com/gobuffalo/buffalo/pull/1216
  * https://github.com/gobuffalo/buffalo/pull/1216/files#diff-ac069b752eca30067e98020f2707cd0f30063fe516596330ce41a384ad62f340
* https://github.com/gobuffalo/plush/pull/68

**Comment by sio4** [comment]
I would like to deprecate this fork if the issue was gone, not now but when we have enough bandwidth to work on this issue.

Currently, it has the following vendorized modules:
- https://github.com/shurcooL/github_flavored_markdown the original module
- https://github.com/shurcooL/highlight_diff
- https://github.com/shurcooL/highlight_go
- https://github.com/shurcooL/octicon
- https://github.com/shurcooL/sanitized_anchor_name
- https://github.com/russross/blackfriday

**Comment by paganotoni** [comment]
@sio4 This is probably related to the topic in this issue: I've been wanting to remove the auto-loading of the helpers in the plush package because these include this dependency. That would imply loading these helpers in Buffalo. Would you happen to have any thoughts on this change?

https://github.com/gobuffalo/plush/blob/main/helpers.go#L22
